In [3]:
import numpy as np


In [5]:
my_list=[1,2,3]

In [7]:
arr=np.array(my_list)

In [12]:
arr

array([1, 2, 3])

In [10]:
mat=[[1,2,3],[4,5,6],[7,8,9]]

In [13]:
np.array(mat)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [19]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [22]:
np.zeros((4,2))

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

In [36]:
np.random.rand(5,4)

array([[0.34730326, 0.84682587, 0.45481611, 0.49834068],
       [0.27271598, 0.81568485, 0.72929173, 0.97082907],
       [0.60341542, 0.67546652, 0.82886282, 0.05005633],
       [0.19851249, 0.78580693, 0.98494563, 0.71214935],
       [0.89437656, 0.06573675, 0.71728718, 0.58871258]])