In [3]:
import numpy as np


In [5]:
my_list=[1,2,3]

In [7]:
arr=np.array(my_list)

In [12]:
arr

array([1, 2, 3])

In [10]:
mat=[[1,2,3],[4,5,6],[7,8,9]]

In [13]:
np.array(mat)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [18]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])