In [3]:
import numpy as np


In [5]:
my_list=[1,2,3]

In [7]:
arr=np.array(my_list)

In [12]:
arr

array([1, 2, 3])

In [10]:
mat=[[1,2,3],[4,5,6],[7,8,9]]

In [13]:
np.array(mat)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [19]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [22]:
np.zeros((4,2))

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

In [32]:
np.random.rand(5,4,10)

array([[[0.75869001, 0.79874345, 0.86641869, 0.91896873, 0.5417989 ,
         0.14012712],
        [0.84795524, 0.41484165, 0.1176806 , 0.64935316, 0.88114412,
         0.52798962],
        [0.55049655, 0.57857033, 0.11077759, 0.46885946, 0.34194228,
         0.04206008],
        [0.09580323, 0.58279146, 0.20933385, 0.35320908, 0.16912754,
         0.73984936]],

       [[0.85748292, 0.16091408, 0.42364778, 0.25893048, 0.49465738,
         0.72015956],
        [0.3494081 , 0.31824793, 0.66771037, 0.84761718, 0.36261255,
         0.50659244],
        [0.81159564, 0.4047556 , 0.37043136, 0.20386126, 0.35834869,
         0.91016546],
        [0.95689675, 0.13498858, 0.25598489, 0.9502646 , 0.13675304,
         0.41047068]],

       [[0.8663159 , 0.95381167, 0.66348068, 0.1186244 , 0.29660014,
         0.80563533],
        [0.25788146, 0.80411714, 0.87141318, 0.54718619, 0.76995971,
         0.78418957],
        [0.12752327, 0.66723278, 0.32370527, 0.21872829, 0.67269674,
         0.470853