In [3]:
import numpy as np


In [5]:
my_list=[1,2,3]

In [7]:
arr=np.array(my_list)

In [12]:
arr

array([1, 2, 3])

In [10]:
mat=[[1,2,3],[4,5,6],[7,8,9]]

In [13]:
np.array(mat)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [19]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [22]:
np.zeros((4,2))

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

In [38]:
np.random.rand(5,4)

array([[0.06908784, 0.00751288, 0.76971721, 0.11249154],
       [0.54977029, 0.81535944, 0.52342896, 0.92176341],
       [0.1731554 , 0.60379773, 0.40816131, 0.28076809],
       [0.08113519, 0.91293945, 0.90022982, 0.98143035],
       [0.6283979 , 0.27150821, 0.90091179, 0.97232101]])

In [42]:
np.random.randint(1,100,10)

array([67, 36,  2, 66, 62, 26, 62, 34, 38, 60])

In [45]:
arr=np.random.randint(1,100,10)

In [47]:
arr

array([22, 29, 22, 45, 84, 84, 57, 13, 52, 47])

In [49]:
arr=np.arange(20)

In [52]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [54]:
arr.reshape(4,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])